### ISSUE TITLE
how to decode service's option object

### ISSUE THREAD

**Issue by ybtuteng** [jhump/protoreflect#232] opened 2019-07-17 09:47 UTC
when i parse a proto file importing "google/api/annotations.proto", i cannot get the correct service's option infomation.
for example, when i create a service like this
![image](https://user-images.githubusercontent.com/12271804/61365326-1b7bea80-a8ba-11e9-9211-2a8b821f425f.png)
i'd like get the "post" key, and it's value which means http path.However, i get the results like that
![image](https://user-images.githubusercontent.com/12271804/61365446-53832d80-a8ba-11e9-9f85-c79f25fe1388.png)
As you can see, all key cannot be corrected parse, which value correct. And I found the first number means the "google.api.http" id in the proto file. But what i care about is the key rather than id. 
Wish reply, thank you!

**Comment by jhump** [comment] 2019-07-17 12:21
@ybtuteng, what are those screenshots from? That looks like the raw decoded form a proto. FWIW, it _does_ look correct: that value is a binary-encoded proto for the whole `google.api.http` message field. If you were to decode those bytes, you'd have a message where the `post` field is that string and also the `body` field is `"*".

Though the title is "incorrect service option" (as if there is a bug in protoreflect), it doesn't look like you're actually using protoreflect. If you are, can you paste some example code to reproduce what you're seeing. I think you may just be using it incorrectly.

Or are you asking how to use protoreflect to get to those options?

**Comment by ybtuteng** [comment] 2019-07-17 12:50
> @ybtuteng, what are those screenshots from? That looks like the raw decoded form a proto. FWIW, it _does_ look correct: that value is a binary-encoded proto for the whole `google.api.http` message field. If you were to decode those bytes, you'd have a message where the `post` field is that string and also the `body` field is `"*".
> 
> Though the title is "incorrect service option" (as if there is a bug in protoreflect), it doesn't look like you're actually using protoreflect. If you are, can you paste some example code to reproduce what you're seeing. I think you may just be using it incorrectly.
> 
> Or are you asking how to use protoreflect to get to those options?

Sorry for my poor english, i just cannot express myself properly.
However, my problem is how to get the actual key of option field. This is my code, i just print all method's option string, which looks like not totally string or binary data
`for _, service := range fd.GetServices() {
		for _, method := range service.GetMethods() {
			fmt.Println(method.GetMethodOptions().String())
		}
	}`
it prints these
`72295728:"\"\r/CreateDeploy:\x01*"
72295728:"\"\r/DeleteDeploy:\x01*"`
my proto looks like this
`syntax = "proto3";
package Package.my_service;
option go_package="pb3/Package/my_service";
import "google/api/annotations.proto";

service ManageService {
    rpc CreateDeploy(CreateDeployReq) returns (CreateDeployRsp) {
        option (google.api.http) = {
                post:"/CreateDeploy"
                body:"*"
            };
    }
}
`
So, if i am not using it correctly, would you mind show me an example?

**Comment by jhump** [comment] 2019-07-17 19:48
That output suggests that your program doesn't know about the extension. So it just prints it as an unknown field (which is why it only shows the tag number and the encoded value, instead of interpreting it in a more meaningful way).

I think would be fixed by just importing the package with that extension:

```
import _ "google.golang.org/genproto/googleapis/api/annotations"
```

In particular, you need the [`E_Http` extension](https://godoc.org/google.golang.org/genproto/googleapis/api/annotations#pkg-variables) loaded from that package (which is done during that package's `init`).

After that, the `String()` method for method options will know about that extension and be able to print the data more meaningfully.

If you then want programmatic access to that extension, you use the [extension-related](https://godoc.org/github.com/golang/protobuf/proto#GetExtension) methods in the `proto` package. For example:

```go
extVal, err := proto.GetExtension(methodOptions, annotations.E_Http)
if err != nil {
  panic(err) // TODO
}
httpRule := extVal.(*annotations.HttpRule)
```

**Comment by jhump** [comment] 2019-07-18 15:14
@ybtuteng, does my last comment address your questions?

**Comment by ybtuteng** [comment] 2019-07-19 08:21
> @ybtuteng, does my last comment address your questions?

I have my problem solved. Thanks very much!
I fixed it like that

```
    rule := &annotations.HttpRule{}
    var data []byte
    data, err = method.GetMethodOptions().XXX_Marshal(data, false)
    if err != nil {
        panic(err)
    }
    err = proto.Unmarshal(data, rule)
    if err != nil {
        panic(err)
    }
```
It makes me get a HttpRule object which contains all field I need. But when  I use another code like this to marshal before unmarshal, it always get a empty object
```
    data, err := proto.Marshal(method.GetMethodOptions())
    if err != nil {
        panic(err)
    }
```
So, how's the difference between `proto.Marshal()`  and `message.XXX_Marshal()`?

**Comment by jhump** [comment] 2019-07-19 12:06
@ybtuteng, did you try using `proto.GetExtension`? That is the correct way to do this. You do not need to marshal the options at all. Just retrieve the extension directly from the `method.GetMethodOptions()` message.

I don't actually know how what you're doing works. It doesn't really make sense to me that either approach would work -- you are marshaling options but then trying to unmarshal that same data as if the marshaled message were just the one custom option.

**Comment by hitzhangjie** [comment] 2019-08-05 08:04
Hi, I come across a similar problem:

```protobuf
syntax = "proto3";
import "google/protobuf/descriptor.proto";
package helloworld;


// Hello
message HelloRequest {}
message HelloResponse{}

// Bye
message ByeRequest {}
message ByeResponse {}

// trpc desc
message TRPC {
    string rpc_name = 1;
}

extend google.protobuf.MethodOptions {
    TRPC trpc = 50000;
}

extend google.protobuf.MethodOptions {
    string rpc_name = 50001;
}

// service: greeter
service greeter {
    rpc SayHello ( HelloRequest )    returns ( HelloResponse ) { option (trpc).rpc_name = "/aaaaaa"; }
    rpc SayBye   ( ByeRequest   )    returns ( ByeResponse   ) { option (rpc_name) = "/bbbbbb"; };
}
```

Following is my go code:

```go
// fd is the FileDescriptorProto
service := fd.GetServices()[0]
for idx, m := range service.GetMethods() {
	fmt.Println(m.GetMethodOptions())
        ...
}
```

The output is as following:
```bash
50000:"\n\a/aaaaaa"
50001:"/bbbbbb"
```

I think, the message `TRPC` is defined in current *.proto, protoreflect may should find the extension key `TRPC.rpc_name` instead of tag number `50000`.

Did I miss something? I tried `fd.GetExtensions()`, it can get the definitions, but I don't know how to associate the extension definition and methodOptions.

**Comment by hitzhangjie** [comment] 2019-08-05 08:14
It looks like I should provide a `&proto.ExtensionDesc{}`?

**Comment by hitzhangjie** [comment] 2019-08-05 09:07
Ah, If I have two MethodOptions in `helloworld.proto` like this:

```protocol
service greeter {
   rpc SayHello(HelloRequest) returns(HelloResponse) {
       option (trpc.TRPC).rpc_name = "/aaaaa";
       option (trpc.rpc_name) = "/bbbbb";
  }
}
```

in go code:
```go
// Now I want to only support this option, but users may provide more options like I do before,
// if so, the code here will fail, should we only parse the option specified by `trpc.E_rpcName`
// rather than return an error?
v, err := proto.GetExtension(m.GetMethodOptions(), trpc.E_RpcName)


```

**Comment by jhump** [comment] 2019-08-08 20:15
@ybtuteng, is there anything else you need, or can I close this issue?

**Comment by jhump** [comment] 2019-08-21 01:00
Closing this issue since I got no response to my last ping. Re-open and add a comment if you are still having issues.

**Closed by jhump** 2019-08-21 01:00 UTC
