### ISSUE TITLE
LoadFileDescriptor with dependency proto failed with wrong path

### ISSUE THREAD

**Issue by navono** [jhump/protoreflect#336] opened 2020-07-07 07:44 UTC
# Env
OS: Win 10 1909
protoreflect Version: 1.7.0

# Description
I have a proto file,  contains some other proto dependencies like: gogole standard proto. 
Use `desc.LoadFileDescriptor(xx/yy/custom.proto)`  will failed.

in `imports.go`, it will translate proto file path:

```
func ResolveImport(importPath string) string {
	importPath = clean(importPath)
	globalImportPathMu.RLock()
	defer globalImportPathMu.RUnlock()
	reg := globalImportPathConf[importPath]
	if reg == "" {
		return importPath
	}
	return reg
}

func clean(path string) string {
	if path == "" {
		return ""
	}
	path = filepath.Clean(path)
	if path == "." {
		return ""
	}
	return strings.TrimPrefix(path, dotPrefix)
}
```

for example, from "google/protobuf/any.proto" to "google\protobuf\any.proto", cause not found in `filesCache`.

**Comment by jhump** [comment] 2020-07-07 15:43
Duplicate of #335

**Closed by jhump** 2020-07-07 15:43 UTC
