### ISSUE TITLE
Getting Nil deference when using custom data type in message

### ISSUE THREAD

**Issue by krtkvrm** [jhump/protoreflect#468] opened 2021-12-08 20:12 UTC
We are trying to make middleware that will extract the string out of grpc proto message on the fly using unmarshaling. Currently we are just building 100 string fields on which we marshal the porto message as []byte.
But now we are trying to make a nested form where I want to extract 
- 1st field `(hello)` of 4th field `(h)` of `helloRequest`
- nth element of 2nd field `(greeting)` of 4th field `(h)` of `helloRequest`

We are trying to use https://github.com/jhump/protoreflect/issues/318 to make a query and extract out string values
Proto file is below for client/server:

proto:
```proto
syntax = "proto3";

package hello;
option go_package = "proto/v1";

message helloRequest {
  string addr = 1;
  repeated string name = 2;
  repeated string age = 3;
  helloResponseNested h = 4;
}

message helloResponseNested {
  string hello = 1;
  string greeting = 2;
}

message helloResponse {
  string hello = 1;
  repeated string greeting = 2;
}

service helloService {
  rpc Hello(helloRequest) returns (helloResponse) {};
}

```

We are trying to build sub message `sub_message` using `NewMessage` to add fields and then use `builder.FieldTypeMessage` to use sub_message in the main message. But when we run the Unmarshal(), we get nil panic, which is **recovered**, but its behaving not expected. We are getting random elements of repeated field when using `TryGetFieldByNumber`

code:
```go

builderMsg := builder.NewMessage("shield")

nestedMsg := builder.NewMessage("sub_message").AddField(builder.NewField("_1", builder.FieldTypeScalar(descriptor.FieldDescriptorProto_TYPE_STRING)).SetNumber(1))
builderMsg = builderMsg.AddField(builder.NewField("_2", builder.FieldTypeMessage(nestedMsg)).SetNumber(4))

msgDescriptor, err := builderMsg.Build()
if err != nil {
		return nil, err
}

dynamicMsgKey := dynamic.NewMessage(msgDescriptor)
if err := dynamicMsgKey.Unmarshal(msg); err != nil {
		return "", err
}
```

catching at [dynamic/dynamic_message.go#L219](https://github.com/jhump/protoreflect/blob/master/dynamic/dynamic_message.go#L219)
![image](https://user-images.githubusercontent.com/3920286/145276162-8719cec1-19f3-473c-bbe0-4efff5a308b4.png)

Thanks !

**Comment by jhump** [comment] 2021-12-09 04:13
The panic and the recovery are all inside of the protobuf runtime, right? I think that is expected.

I'm afraid it's a bit unclear what the problem is from your description. Is it this I guess?
>  We are getting random elements of repeated field when using `TryGetFieldByNumber`

I would expect you to only ever get the _last_ element. Perhaps they are added to the request from a map, so being inserted in random order?

Anyhow, if you want all of the values, you have to mark the field as repeated when you are building it via a call to `SetRepeated()` on the `FieldBuilder`.

**Comment by krtkvrm** [comment] 2021-12-09 05:14
i think that the proto
```proto
message helloRequest {
  helloResponseNested h = 4;
}

message helloResponseNested {
  string hello = 1;
}
```
is not as same as 
```go
builderMsg := builder.NewMessage("shield")

nestedMsg := builder.NewMessage("sub_message").AddField(builder.NewField("_1", builder.FieldTypeScalar(descriptor.FieldDescriptorProto_TYPE_STRING)).SetNumber(1))
builderMsg = builderMsg.AddField(builder.NewField("_2", builder.FieldTypeMessage(nestedMsg)).SetNumber(4))
```
as I am getting panic and recovery. Can you help me correcting this ?

**Comment by krtkvrm** [comment] 2021-12-09 07:26
I tried printing the files and am getting this
```
File Name:  {generated-file-0001}.proto
=============================
syntax = "proto2";

message sub_message {
  optional string _1 = 1;
}
-------------------------------------------------------------------------------
File Name:  {generated-file-0002}.proto
============================
syntax = "proto2";

import "{generated-file-0001}.proto";

message shield {
  optional sub_message _2 = 4;
}

```
code:
```go

builderMsg := builder.NewMessage("shield")

nestedMsg := builder.NewMessage("sub_message").AddField(builder.NewField("_1", builder.FieldTypeScalar(descriptor.FieldDescriptorProto_TYPE_STRING)).SetNumber(1))
builderMsg = builderMsg.AddField(builder.NewField("_2", builder.FieldTypeMessage(nestedMsg)).SetNumber(4))


msgDescriptor, err := builderMsg.Build()
if err != nil {
	return nil, err
}


protoPrinter := &protoprint.Printer{}
fmt.Println("File Name: ", msgDescriptor.GetFile().GetDependencies()[0].GetFile().GetName())
str, err := protoPrinter.PrintProtoToString(msgDescriptor.GetFile().GetDependencies()[0].GetFile())
fmt.Println(str)
fmt.Println("File Name: ", msgDescriptor.GetFile().GetName())
str, err = protoPrinter.PrintProtoToString(msgDescriptor.GetFile())
fmt.Println(str)
```


So, I feel that there seems to be some issue in Unmarshaling

**Comment by jhump** [comment] 2021-12-09 12:45
The panic and recovery is fine. If it did not recover or returned an error, that would be a problem.

That is simply how the protobuf runtime handles dynamic messages that implement the old v1 `Message` API instead of the new interface. This repo was written for the older runtime API.

**Comment by krtkvrm** [comment] 2021-12-09 13:11
Ok :+1:

**Comment by krtkvrm** [comment] 2022-01-03 03:36
Hi @jhump ,
Is there any timeline to update the library from old v1 Message API?

**Comment by jhump** [comment] 2022-01-05 15:30
Not really a timeline, sorry.

I think a replacement for the `desc/protoparse` stuff is very close to ready. It will be in a separate project: https://github.com/jhump/protocompile.

And I worked on replacements to a few other packages, but in a backwards incompatible way, as a "v2" of this repo. Work in progress is [here](https://github.com/jhump/protoreflect/compare/v2), but that branch is quite old and I only worked up the `codec` and `desc/builder` packages so far. And that `codec` package may not even be relevant/useful anymore since the v2 APIs now include a [protowire](https://pkg.go.dev/google.golang.org/protobuf/encoding/protowire) package.

But I haven't had a lot of time to devote to this. I've mostly been doing maintenance and bugfixes and focusing more effort on `protocompile`.

Once `protocompile` is available, I think it would be safe to rebase and merge #354. That PR will help a _lot_ with compatibility with v2 of the protobuf runtime APIs. I want to wait until after `protocompile` is done because that PR is likely to have a negative performance impact on `desc/protoparse`, so I'd prefer there exist a better solution that protoparse users can migrate to that would recover any lost performance. After that, I may finally get a chance to work more on that v2 branch.

**Closed** 2022-01-11 01:53 UTC
