### ISSUE TITLE
go program run error in debug mode,but could run well with the command go build main.go

### ISSUE THREAD

**Issue by lsk569937453** [jhump/protoreflect#350] opened 2020-09-08 00:51 UTC
my environment is that:
macos
go 1.14
dlv 1.4.1

main.go code is that:
```
package main

import (

	"log"
	"time"
	"bytes"
	"context"
	"fmt"
	"github.com/golang/protobuf/jsonpb"
	"github.com/golang/protobuf/proto"
	"github.com/jhump/protoreflect/dynamic"
	"github.com/jhump/protoreflect/dynamic/grpcdynamic"
	"github.com/jhump/protoreflect/grpcreflect"
	"google.golang.org/grpc"
	reflectpb "google.golang.org/grpc/reflection/grpc_reflection_v1alpha"
	"io"
	"strings"
)

func main()  {
	TestGrpc()
}
func TestGrpc() {
	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Second)
	defer cancel()
	ccReflect, err := grpc.DialContext(ctx, "45.32.63.93:9000", grpc.WithInsecure(), grpc.WithBlock())
	var ext dynamic.ExtensionRegistry
	dataStr := "{}"
	msgFactory := dynamic.NewMessageFactoryWithExtensionRegistry(&ext)
	stub := grpcdynamic.NewStubWithMessageFactory(ccReflect, msgFactory)

	if err != nil {
		log.Println("", err.Error())
	}
	defer ccReflect.Close()
	refClient := grpcreflect.NewClient(context.Background(), reflectpb.NewServerReflectionClient(ccReflect))
	defer refClient.Reset()

	if err != nil {
		log.Println("%s", err.Error())
	}
	service, err := refClient.ListServices()
	log.Println("service List is:%v", service)
	if err != nil {
		log.Println("ListServices error%s", err.Error())
	}
	var realServiceName string
	//filter the reflection service
	for _, item := range service {
		if strings.Contains(item, "reflection") {
			log.Println("service: %s, has been filter", item)
		} else {
			realServiceName = item
		}
	}
	log.Println("realServiceName:%s", realServiceName)
	fileDesc, err := refClient.FileContainingSymbol(realServiceName)
	if err != nil {
		log.Println("FileContainingSymbol error:%s", err)
		return
	}

	//get the service name
	serviceList := fileDesc.GetServices()

	for _, item := range serviceList {
		//get all the mthod description
		methodDescriptions := item.GetMethods()
		for _, methodDescItem := range methodDescriptions {
			methodDescItem.GetName()
			methodDescItem.GetService()
			if methodDescItem.GetName() == "Echo" {
				if methodDescItem.IsServerStreaming() && methodDescItem.IsClientStreaming() {

				} else if methodDescItem.IsServerStreaming() {
					req := msgFactory.NewMessage(methodDescItem.GetInputType())
					jsonpb.Unmarshal(bytes.NewReader([]byte(dataStr)), req)

					tr, err := stub.InvokeRpcServerStream(ctx, methodDescItem, req)
					//	tr, err := stub.InvokeRpcServerStream(ctx, methodDescItem, data)
					if err != nil {
						log.Println("%s", err.Error())
					}
					for {
						var resp proto.Message
						resp, err = tr.RecvMsg()
						if err == io.EOF {
							fmt.Println("find eof and exit")
							break
						}
						if err != nil {
							fmt.Printf("error %v", err)
							return
						}
						fmt.Printf("%v", resp.String())
					}
				} else {
				}
			}
		}
	}
}
```

go.mod is this
```
module atest

go 1.13

require (
	github.com/golang/protobuf v1.4.2
	github.com/jhump/protoreflect v1.7.0
	golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3 // indirect
	google.golang.org/grpc v1.31.1
)

```

the error is this:![](https://i.pinimg.com/originals/4a/09/eb/4a09ebdc7c039668fcc0d76233b1534a.png)

**Comment by jhump** [comment] 2020-09-08 20:33
The fact it works fine using `go build ...` shows that the code works fine. The issue is that you have your IDE trapping all panics, including caught ones. And the Go protobuf runtime uses this panic as a sort of control flow.

This is a duplicate of #341.

**Closed by jhump** 2020-09-08 20:33 UTC

**Comment by lsk569937453** [comment] 2020-09-08 23:53
Thank you very much.I have downgrade the github.com/golang/protobuf from the 1.4.0 to 1.3.5 ,and the code could run well.
