### ISSUE TITLE
Panic with latest golang/protobuf v2

### ISSUE THREAD

**Issue by bufdev** [jhump/protoreflect#387] opened 2021-03-09 21:29 UTC
```
panic: no such file: "google/protobuf/any.proto"

goroutine 1 [running]:
github.com/jhump/protoreflect/desc/protoparse.init.1()
	/Users/foo/.cache/core/Darwin/x86_64/go/pkg/mod/github.com/jhump/protoreflect@v1.8.3-0.20210302193947-8255811fc3c0/desc/protoparse/std_imports.go:46 +0x2c6
```

This is using https://github.com/protocolbuffers/protobuf-go/commit/839ce436895b59ff32f47ca10a6ae33f3f0603e2

I'll investigate a bit more, but I thought you might know right away.

**Comment by bufdev** [comment] 2021-03-09 22:58
I think it has to do with blank importing the ptypes in https://github.com/jhump/protoreflect/blob/master/desc/protoparse/std_imports.go and them not being available anymore in v1? There might have to be something fancy done here.

**Comment by jhump** [comment] 2021-03-10 15:38
Easy to repro: After running `go get google.golang.org/protobuf/proto@839ce43` in this repo, to update the `go.mod` file, the tests immediately start failing with that panic.

So something has changed in the proto runtime. I'll poke around more right now.

**Comment by jhump** [comment] 2021-03-10 15:41
Actually, I see _lots_ of panics in this test output -- with what appears to be _all_ of the protobuf files that should be linked in (even my test protos), not just the standard "well known" ones.

So this must be a breaking change with the global file registry or how it is integrated into the old runtime packages (for backwards-compatibility).

I'm going to do a `git bisect` to figure out when it was introduced.

**Comment by jhump** [comment] 2021-03-10 16:11
It turns out that the panic was introduced in that exact commit: https://github.com/protocolbuffers/protobuf-go/commit/839ce436895b59ff32f47ca10a6ae33f3f0603e2

And the reason is because that commit actually _depends_ on this other commit from the other repo: https://github.com/golang/protobuf/commit/acacf8158c9a307051c92dc233966e8324facd45

I added a comment, to let them know they need to update their `go.mod` files to fix the relationship between these two modules. I assume they may not have done that because neither repo has seen a release in quite some time.  Hopefully it will be addressed in time for their next releases🤞 

In the meantime, @bufdev, you need to also use that above sha for the old `github.com/golang/protobuf` module to make it work again.

I confirmed that after reproducing the panic, the following makes the panic go away:
```
go get github.com/golang/protobuf/proto@acacf81
```

**Comment by jhump** [comment] 2021-04-28 16:22
I think this can be closed. Now that upstream has issued proper releases, the releases have updated cross-repo references to make this all work. The problem before was that an unreleased version of one repo _depended_ on changes in the other repo, but did not state that dependency via an update in `go.mod`. So this was an issue in the protobuf runtime projects, not protoreflect.

**Closed** 2022-02-05 17:08 UTC
